name = "audio_player_with_waveform"
version = "0.1.0"
target = "javascript"

description = "Self-contained audio player with waveform visualization for Lustre. Embed as custom element, pass a URL, done."
licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }

[dependencies]
gleam_stdlib = ">= 0.71.0 and < 2.0.0"
lustre = ">= 5.5.2 and < 6.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[tools.lustre.dev]
host = "0.0.0.0"
